### ISSUE TITLE
use typescript  it's show error TS1192: Module '"http"' has no default export.

### ISSUE THREAD

**Issue by polo13999** [fridays/next-routes#157]
when I upgrade version, it has the error message

 
node_modules/next-routes/typings/next-routes.d.ts(1,8): error TS1192: Module '"http"' has no default export.

**Comment by fridays** [comment]
ping @disintegrator can you help?

**Comment by disintegrator** [comment]
Yep will do

**Comment by disintegrator** [comment]
@polo13999 are you able to add `"esModuleInterop": true` to your tsconfig? next.js typings require this setting from us now...

**Comment by disintegrator** [comment]
@polo13999, @fridays i'm still investigating this but will need a little more time so far it seems esModuleInterop needs to be `false` in order to consume nextjs's typings. This is the test config we use:

```json
{
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "noEmit": true,
    "jsx": "react",
    "strict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "moduleResolution": "node"
  }
}
```

It may be a case of mention something about using with typescript in the README. I'll try and find a final solution later today

**Comment by disintegrator** [comment]
@polo13999 we’ve attempted to address this issue in #158 can you please update to 1.4.1 and try again?
