### ISSUE TITLE
Differences between query routes

### ISSUE THREAD

**Issue by Javier1177** [fridays/next-routes#281]
Hello, I'm working on a project that uses a lot of different languages. So I need to change the language url. Example: 

> www.example.com/es/entradas
> www.example.com/en/tickets
> www.example.com/de/eintrittskarten

There are a lot of url and I'm working with a CMS, so my clients will be able to add more, so it can't be harcoded. I thought to pass the url with queries, like this:

```
const routes = require('next-routes');

module.exports = routes()
  .add('index', '/:lang?')
  .add('tickets', '/:lang?/:ticket')
  .add('hotel', '/:lang?/:hotel');
```
My surprise (as you might see), it doesn't work because routes doesn't see the difference between these two last routes. If I write:

> www.example.com/en/tickets

 It will go correctly to my page ### tickets but if I write 

> www.example.com/en/hotel

It will go again to my page ### tickets and not to ### hotel

Do you know any way about how could I make this?

**Comment by fridays** [comment]
It can't differentiate these URLs because they use the same pattern. You can either put the type of content into the pattern, like /en/hotel/hotel-slug and /en/ticket/123

Or you can use the same pattern and page for the different types, and then inside the page component find the content by slug and from there choose the component to render for that type of content

The first route that matches the URL will be used:
