### ISSUE TITLE
/:slug matches on /__webpack_hmr

### ISSUE THREAD

**Issue by sedubois** [fridays/next-routes#6]
With 1.0.15: 

`routes.js`:
```js
const nextRoutes = require('next-routes');
module.exports = nextRoutes()
  .add('/')
  .add('about')
  .add('discover')
  .add('retreat', '/retreat/:id')
  .add('track', '/track/:id')
  .add('profile', '/:slug');
```

This code:
```js
const { route, params } = routes.match(req.url);
console.log('Found next-routes: ', route, params);
```

(among other things) returns the log below:
<details>

```
Found next-routes:  Route {
  name: 'profile',
  pattern: '/:slug',
  page: '/profile',
  keys: 
   [ { name: 'slug',
       prefix: '/',
       delimiter: '/',
       optional: false,
       repeat: false,
       partial: false,
       asterisk: false,
       pattern: '[^\\/]+?' } ],
  regex: { /^\/((?:[^\/]+?))(?:\/(?=$))?$/i keys: [ [Object] ] },
  getAs: [Function] } { slug: '__webpack_hmr' }
```
</details>

`/:slug` matches on `__webpack_hmr`, which it shouldn't.

Also not sure if it does or not, but should also ensure it won't match on /favicon.ico either.

**Comment by fridays** [comment]
`.match()` is an internal function that matches a string against all registered patterns, in the case of a catch-all route this is expected behavior for that function.

If you use `routes.getRequestHandler(app)` like documented in the readme, that path won't match. It first checks against `routes.isNextPath()` and skips if positive. Please check [how it's implemented here](https://github.com/fridays/next-routes/blob/master/src/index.js#L45-L64). You can use it in a similar way for the caching example.
