### ISSUE TITLE
Add a change log

### ISSUE THREAD

**Issue by jaydenseric** [fridays/next-routes#68]
It would be awesome if a `changelog.md` was added and [Github releases](https://github.com/fridays/next-routes/releases) were used to keep track of changes.

A common practice is to track changes under a `next` version heading at the top of `changelog.md`, then when ready to release:

1. Do a commit bumping the version:
  - New version in `package.json`.
  - Rename the `next` heading in `changelog.md` to the new version.
2. Create a [new Github release](https://github.com/fridays/next-routes/releases/new). Follow the "Tagging suggestions" in the sidebar, and copy-paste the markdown from the change log into the description.
3. Run `npm publish`.

You can see that process in action at [jaydenseric/apollo-upload-client](https://github.com/jaydenseric/apollo-upload-client).

**Comment by fridays** [comment]
Great idea. Thank you for explaining so well.

**Comment by acanimal** [comment]
It would help to work on feature branches instead always over the `master` branch.

**Comment by acanimal** [comment]
@fridays If you agree I can contribute with the changelog.

IMO we could use the [conventional commits](https://conventionalcommits.org) and automatically generate a changelog.md file with the [standard-version](https://github.com/conventional-changelog/standard-version) package.

Benefits:
- Automatically increase package.json version (similar to npm version)
- Automatically create a tag version.
- Generate Changelog.md file with the features, bug fixes, test, etc made since the last version

**Comment by acanimal** [comment]
Just pushed this PR https://github.com/fridays/next-routes/pull/78

Is really easy to use and project would benefit from having tag releases and changelogs.

**Comment by fridays** [comment]
Thank you, that looks very useful. [semantic-release](https://github.com/semantic-release/semantic-release) and [zeit/release](https://github.com/zeit/release) sound good too. Anyone experience with the pros and cons?

**Comment by fridays** [comment]
I just made a github release using `release`, that was easy. Thanks again!
